site_name: measured
repo_url: https://github.com/chrisguidry/measured/
theme: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_root_toc_entry: false
          show_signature_annotations: true
watch:
- docs
- src
nav:
- index.md
- 'Systems of Measurement':
  - si.md
  - fundamental.md
  - iec.md
  - astronomical.md
  - us.md
  - avoirdupois.md
  - troy.md
- formatting.md
- serialization.md
